version: '3.8'

services:
  app:
    build: .
    container_name: chat
    volumes:
      - db:/var/www/html
    ports:
      - 8080:8080

  tests:
    build: ./tests
    container_name: tests
    depends_on:
      - app

volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/chat