version: '3.8'

services:
  app:
    build: .
    volumes:
      - db:/var/www/html
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /$HOME/data/chat